export type Civ = {
  name: string
  icon: string
}

export const civs: Civ[] = [
  { name: "Azteken", icon: "aztecs.png" },
  { name: "Berber", icon: "berber.png" },
  { name: "Böhmen", icon: "bohemians.png" },
  { name: "Briten", icon: "britons.png" },
  { name: "Bulgaren", icon: "bulgarians.png" },
  { name: "Burgunder", icon: "burgundians.png" },
  { name: "Birmanen", icon: "burmese.png" },
  { name: "Byzantiner", icon: "byzantines.png" },
  { name: "Kelten", icon: "celts.png" },
  { name: "Chinesen", icon: "chinese.png" },
  { name: "Kumanen", icon: "cumans.png" },
  { name: "Äthiopier", icon: "ethiopians.png" },
  { name: "Franken", icon: "franks.png" },
  { name: "Goten", icon: "goths.png" },
  { name: "Hunnen", icon: "huns.png" },
  { name: "Inka", icon: "inca.png" },
  { name: "Inder", icon: "indians.png" },
  { name: "Italiener", icon: "italians.png" },
  { name: "Japaner", icon: "japanese.png" },
  { name: "Khmer", icon: "khmer.png" },
  { name: "Koreaner", icon: "koreans.png" },
  { name: "Litauer", icon: "lithuanians.png" },
  { name: "Ungarn", icon: "magyars.png" },
  { name: "Malier", icon: "malay.png" },
  { name: "Malaien", icon: "malians.png" },
  { name: "Maya", icon: "mayans.png" },
  { name: "Mongolen", icon: "mongols.png" },
  { name: "Perser", icon: "persians.png" },
  { name: "Polen", icon: "poles.png" },
  { name: "Portugiesen", icon: "portuguese.png" },
  { name: "Sarazenen", icon: "saracens.png" },
  { name: "Sizilianer", icon: "sicilians.png" },
  { name: "Slawen", icon: "slavs.png" },
  { name: "Spanier", icon: "spanish.png" },
  { name: "Tataren", icon: "tatars.png" },
  { name: "Teutonen", icon: "teutons.png" },
  { name: "Türken", icon: "turks.png" },
  { name: "Vietnamesen", icon: "vietnamese.png" },
  { name: "Wikinger", icon: "vikings.png" },
]
